[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.17" # Solana version to use

[features]
seeds = true

[registry]
url = "https://api.apr.dev"

[workspace]
members = [
    "programs/merkle-distributor",
]

[provider]
cluster = "devnet"
wallet = "/Users/sebsol/00_Dev-Projects/00_Personal-Proj/00_DevWallets/MADVnaXAar2EBsKpdCn3UUc9HkCNxWZNkxqXqiGbxi9.json"

[programs.mainnet]
merkle_distributor = "m1uqAm3yAagng3uqphvQ4rRAkRy17F4JX87pFemLBKv"

[programs.devnet]
merkle_distributor = "m1uqAm3yAagng3uqphvQ4rRAkRy17F4JX87pFemLBKv"

[programs.testnet]
merkle_distributor = "m1uqAm3yAagng3uqphvQ4rRAkRy17F4JX87pFemLBKv"

[programs.localnet]
merkle_distributor = "m1uqAm3yAagng3uqphvQ4rRAkRy17F4JX87pFemLBKv"

[scripts]
test = "yarn mocha"
